---
- name: Configure host.
  hosts: all
  become: yes

  vars_files:
    - default.config.yml

  roles:
    - geerlingguy.docker
    - rolehippie.starship

  pre_tasks:
    - name: Ensure the locale exists
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

    - name: Apt Install required softwares
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg: ['git', 'vim', 'tmux', 'zip', 'unzip', 'build-essential', 'cmake', 'fzf', 'gnupg2',
              'flatpak', 'gnome-software-plugin-flatpak',
              'curl', 'net-tools', 'apt-transport-https', 'ca-certificates']
        state: present

    - name: Install nvim use snap.
      community.general.snap:
        name: nvim
        classic: true

    # https://stackoverflow.com/a/26399105/157811
    - name: get the username running the deploy
      become: false
      action: command whoami
      register: current_username

    - name: Ensure dotconfig directory exists.
      become: false
      file:
        path: /home/{{ current_username.stdout }}/.config
        state: directory

    - name: Dot config git directory.
      stat:
        path: /home/{{ current_username.stdout }}/.config/.git
      register: dotconfig_git

    - include_tasks: tasks/fishshell.yml


  tasks:
    - include_tasks: tasks/zoxide.yml
    - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/kitty.yml

    - name: Setup dotconfig
      become: false
      command: "{{ item }}"
      args:
        chdir: /home/{{ current_username.stdout }}/.config
      with_items:
        - "git init"
        - "git remote add origin https://github.com/harryxu/dotconfig.git"
        - "git fetch"
        - "git checkout origin/main -ft"
        - "git submodule init"
        - "git submodule update"
      when: not dotconfig_git.stat.exists

    - name: Change user shell to fish
      user:
        name: "{{ current_username.stdout }}"
        shell: /usr/bin/fish
