---

- name: Ensure fonts directory
  become: false
  file:
    path: "/home/{{ current_username.stdout }}/.fonts"
    state: directory

- name: Check and nerd fonts exists.
  become: false
  vars:
    fonts:
      # `pkg` for font package name while download
      # `check` for font file to check font exists
      - { pkg: UbuntuMono, check: "UbuntuMonoNerdFontMono-Regular.ttf" }

  stat:
    path: "/home/{{ current_username.stdout }}/.fonts/{{ item.check }}"
  register: nerdfonts_stat_results
  with_items: "{{ fonts }}"
  ignore_errors: True

- name: Download and extract nerd font
  become: false
  unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item.item.pkg }}.tar.xz"
    dest: "/home/{{ current_username.stdout }}/.fonts/"
    remote_src: yes
  with_items: "{{ nerdfonts_stat_results.results }}"
  when: item.stat.exists == False

