---
- set_fact:
    theme_pack: Nightfox-GTK-Theme
    theme_icon: Duskfox-Alt-3
    # gnome_theme:
    theme_install_options: "--tweak nord float macos -l"

- debug:
    msg: "Icon them: {{ theme_icon }}"

- name: Ensure theme related directories exists.
  become: false
  file:
    path: /home/{{ current_username.stdout }}/{{ item }}
    state: directory
  with_items:
    - ".icons"
    - ".themes"

- name: Icon folder
  become: false
  stat:
    path: /home/{{ current_username.stdout }}/.icons/{{ theme_icon }}
  register: them_icon_dir

- name: Download and install theme.
  block:

    - name: Download and Unzip the theme file
      unarchive:
        src: "https://github.com/Fausto-Korpsvart/{{ theme_pack }}/archive/refs/heads/main.zip"
        dest: /tmp/
        remote_src: yes

    - name: Copy Icon themes.
      command: cp -a ./icons/. /home/{{ current_username.stdout }}/.icons/
      args:
        chdir: "/tmp/{{ theme_pack }}-main"

    - name: Set Icon theme.
      command: gsettings set org.gnome.desktop.interface icon-theme '{{ theme_icon }}'

    # - name: Run the install.sh script
    #   command: ./install.sh {{ theme_install_options }}
    #   args:
    #     chdir: /tmp/themepack/themes/
  when: not them_icon_dir.stat.exists
  become: false
